apiVersion: apps/v1
kind: Deployment
metadata:
  name: keypair-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keypair-agent
  template:
    metadata:
      labels:
        app: keypair-agent
    spec:
      serviceAccountName: keypair
      containers:
        - name: keypair-agent
          image: <your-dockerhub>/keypair-agent:example
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: KEYPAIR_SERVICE_ACCOUNT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: keypair-secret
                  key: token
