apiVersion: v1
kind: ConfigMap
metadata:
  name: keypair-user-mapping
data:
  # Update this with your user-to-key mappings
  user1: ssh-rsa AAAA...22OGwH user1@host
  user2: ssh-rsa AAAA...Hvu9d3 user2@host
